### PR TITLE
Replace rental with ouroboros

### PR DESCRIPTION
**Pull request by est31**
rental is not maintained any more and users
are encouraged to switch to alternatives.

### CODE REVIEW

**Comment by est31** [comment]
closing in favour of #46. Hadn't noticed it lol.

**Comment by wezm** [comment]
Feel free to reopen. We haven't decided on the preferred way forward yet.

**Comment by Voultapher** [comment]
What a curious coincidence :D

**Comment by wezm** [comment]
Thanks for this. It was merged in manually as 7b51ea85e27004b55ebdc86e60da24f149503fb5.

**Pull request closed without merging**
