### PR TITLE
Fix #39

### LINKED ISSUE #39: Derive Copy + Clone for MaxpTable and CmapSubtable
Also it would be great if `lookup_glyph_index` was on the `owned::CmapSubtable` - together with conversion function to convert from a `CmapSubtable<'a>` to an `owned::CmapSubtable` and back - this way users can cache the `CmapSubtable` if needed.

I'm trying to create a struct that "owns" the cmap subtable, but if I create an `OwnedCmapSubtable` then looking up glyphs isn't available anymore

### PR DESCRIPTION
**Pull request by fschutt**
NOTE: The code for `.map_glyph` is duplicated, which isn't great. I can't create a `ReadArray<T>` from a `Vec<T>`, so I can only either duplicate the code or use a macro.

### CODE REVIEW

**Comment by wezm** [comment]
I'm not sure I really want `is_mark` to be public again. Ideally it would remain an implementation detail. What was your use case for making it public? The pattern I'm using in the code I'm working on at the moment is along these lines:

```rust
        let position = match info.mark_placement {
            MarkPlacement::None => {
                match info.placement {
                    Placement::None => (x, y),
                    Placement::Distance(dx, dy) => (x + dx, y + dy),
                    Placement::Anchor(_, _) => (x, y), // FIXME: position anchors for cursive
                };
            }
            MarkPlacement::MarkAnchor(base_index, x, y) => {
                unimplemented!()
            }
            MarkPlacement::MarkOverprint(base_index) => {
                positions[base_index];
            }
        };
```

Did you have a particular need for making the various types `Copy`? Typically I reserve Copy for smaller types (that fit in a register or two) to avoid surprise `memcpy`s. 

Here are the sizes (in bytes) of some of the types: HeadTable = 56, TableRecord = 16 HheaTable = 22, MaxpTable = 30, MaxpVersion1SubTable = 26

**Comment by fschutt** [comment]
I'm okay with not implementing Copy, but I need them to be at least Clone, because my implementation doesn't store the entire font, it only stores a few tables. So I can either parse the tables again or I could simply clone them from the font provider.

My usecase for `is_mark` is that I want to switch the positioning between `MarkPlacement` and `Placement`. I can make it a function that returns true on `MarkPlacement::None`, it's just that I wanted my code to build yesterday evening

**Comment by wezm** [comment]
> My usecase for is_mark is that I want to switch the positioning between `MarkPlacement` and `Placement`.

So after going through the process of adding positioning info to the `allsorts-tools` shape command I don't think it's quite this simple: if a mark is attached to a base glyph with `Placement::Distance` then the mark also needs to be adjusted by that distance:

https://github.com/yeslogic/allsorts-tools/pull/14/files#diff-f686acba59f5e44ba9e3177784a8c42d45806e266474c5540305fd33dad01f40R64-R70

**Comment by wezm** [comment]
I merged a number of these changes manually. I had to drop the derived `Debug` and `PartialEq` impls on the cmap types as these don't work in Rust 1.38.0, which is the minimum version we support. Are these required for your use case?

**Comment by fschutt** [comment]
No, not required, I just added it because it does make things easier for testing. `Clone` is the most important trait.

Thanks for mergin.

**Pull request closed without merging**
